name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: pip install -r dev-requirements.txt
    - name: Lint scraper
      run: flake8 scrape.py
    - name: Scrape data
      run: python3 scrape.py
    - name: Build site
      run: mkdocs build --verbose
